name: Generate Readme Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: vncp/github-readme-stats-action@main
        with:
          show_icons: true
          theme: dracula
          include_all_commits: true
          count_private: true
          langs_count: 7
          output_dir: generated-stats

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add generated-stats/
          git diff-index --quiet HEAD || git commit -m "Update stats"
          git push
